### ISSUE TITLE
Ender Tank NEI Crash / Forge Problem?

### ISSUE THREAD

**Issue by Tsunayoshi** [Tsunayoshi/Server#18]
Forge 10.13.3.1369

**Comment by Tsunayoshi** [comment]
[00:57:27] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel ES
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
        at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29) ~[FluidStack.class:?]
        at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59) ~[FluidStack.class:?]
        at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18) ~[ExtendedFluidTank.class:?]
        at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28) ~[ExtendedFluidTank.class:?]
        at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:21) ~[EnderLiquidStorage$Tank.class:?]
        at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:34) ~[EnderLiquidStorage.class:?]
        at codechicken.enderstorage.storage.EnderLiquidStoragePlugin.createEnderStorage(EnderLiquidStoragePlugin.java:16) ~[EnderLiquidStoragePlugin.class:?]
        at codechicken.enderstorage.api.EnderStorageManager.getStorage(EnderStorageManager.java:161) ~[EnderStorageManager.class:?]
        at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.track(TankSynchroniser.java:170) ~[TankSynchroniser$PlayerItemTankCache.class:?]
        at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.handleVisiblityPacket(TankSynchroniser.java:232) ~[TankSynchroniser$PlayerItemTankCache.class:?]
        at codechicken.enderstorage.storage.liquid.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:269) ~[TankSynchroniser.class:?]
        at codechicken.enderstorage.internal.EnderStorageSPH.handlePacket(EnderStorageSPH.java:20) ~[EnderStorageSPH.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:115) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Tsunayoshi** [comment]
https://github.com/Chicken-Bones/EnderStorage/issues/36

**Comment by Tsunayoshi** [comment]
Update auf Forge 1370

**Comment by Tsunayoshi** [comment]
[01:15:14] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel ES
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
        at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29) ~[FluidStack.class:?]
        at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59) ~[FluidStack.class:?]
        at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18) ~[ExtendedFluidTank.class:?]
        at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28) ~[ExtendedFluidTank.class:?]
        at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:21) ~[EnderLiquidStorage$Tank.class:?]
        at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:34) ~[EnderLiquidStorage.class:?]
        at codechicken.enderstorage.storage.EnderLiquidStoragePlugin.createEnderStorage(EnderLiquidStoragePlugin.java:16) ~[EnderLiquidStoragePlugin.class:?]
        at codechicken.enderstorage.api.EnderStorageManager.getStorage(EnderStorageManager.java:161) ~[EnderStorageManager.class:?]
        at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.track(TankSynchroniser.java:170) ~[TankSynchroniser$PlayerItemTankCache.class:?]
        at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.handleVisiblityPacket(TankSynchroniser.java:232) ~[TankSynchroniser$PlayerItemTankCache.class:?]
        at codechicken.enderstorage.storage.liquid.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:269) ~[TankSynchroniser.class:?]
        at codechicken.enderstorage.internal.EnderStorageSPH.handlePacket(EnderStorageSPH.java:20) ~[EnderStorageSPH.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:115) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Tsunayoshi** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html
http://chickenbones.net/Pages/links.html

**Comment by Tsunayoshi** [comment]
Update 5.8-003
